#!/bin/sh
# xync-init

# Copyright (c) 2026, Victor Tschetter.
# All rights reserved.

# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the name of the developer nor the names of contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.

# THIS SOFTWARE IS PROVIDED BY THE DEVELOPER ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE DEVELOPER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.

# Set environment.
PATH=${PATH}:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin

# Determine full working directory.
CWDIR=$(dirname $(realpath $0))

# Global variables.
APP="Xync"
APP_NAME="xync"
APP_DIR=$(echo "${CWDIR}" | grep -o '[^/]*$')
APP_INIT=$(basename $0) 
APP_COMMAND="xync.sh"
APP_CONFIG="${CWDIR}/conf/${APP_NAME}.conf"
APP_DIST="${CWDIR}/${APP_NAME}-dist"
EXT_CONFIG="${APP_NAME}.conf.ext"
XIGMANAS_CONFIG="/cf/conf/config.xml"
USRLOCAL="/usr/local"
WWW="${USRLOCAL}/www"
INSTALL_PATH="${CWDIR}"
APP_BRANCH="main"
EXT_BRANCH="main"
EXT_URL="https://github.com/tschettervictor/xigmanas-${APP_NAME}-extension/archive/${EXT_BRANCH}.zip"
APP_URL="https://github.com/tschettervictor/${APP_NAME}/archive/${APP_BRANCH}.zip"
EXT_VERSION_FILE="https://raw.githubusercontent.com/tschettervictor/xigmanas-${APP_NAME}-extension/${EXT_BRANCH}/version"

install_extension() {
	if [ ! -d "${APP_DIST}" ]; then
		echo "Fetching ${APP} extension..."
		fetch -ao ${CWDIR}/${EXT_BRANCH}.zip --no-verify-peer --timeout=30 ${EXT_URL} || echo "[ERROR]: A problem has occurred while fetching ${APP} extension."
		echo "Extracting ${APPNAME}..."
		if [ -f "${APP_CONFIG}" ]; then
			tar -xf ${CWDIR}/${EXT_BRANCH}.zip --exclude='.git*' --strip-components 1 -C ${CWDIR} || \
			echo "[ERROR]: A problem has occurred while extractig ${APP} extension files."
		else
			tar -xf ${CWDIR}/${EXT_BRANCH}.zip --exclude='.git*' --strip-components 1 -C ${CWDIR} || \
			echo "[ERROR]: A problem has occurred while extractig ${APPNAME} files."
            cp "${CWDIR}/conf/xync.conf.sample" "${APP_CONFIG}"
		fi
		rm -f ${CWDIR}/${EXT_BRANCH}.zip
		echo "Extension Installed!"
	fi
}

update_extension() {
	echo "Looking for new extension version..."
	mkdir -p ${CWDIR}/update
	fetch -ao ${CWDIR}/update --no-verify-peer --timeout=30 ${EXT_VERSION_FILE} || \
	error_notify "Error: A problem has occurred while fetching version file."
	if [ -f "${CWDIR}/update/version" ]; then
		NEW_VERSION=$(cat ${CWDIR}/update/version | tr -d .)
		CURRENT_VERSION=$(cat ${CWDIR}/version | tr -d .)
		if [ "${NEW_VERSION}" -gt "${CURRENT_VERSION}" ]; then
			echo "New extension version found, performing update..."
    		echo "Fetching ${APP} extension..."
	    	fetch -ao ${CWDIR}/${EXT_BRANCH}.zip --no-verify-peer --timeout=30 ${EXT_URL} || \
		    echo "[ERROR]: A problem has occurred while fetching ${APP} extension."
			tar -xf ${CWDIR}/update/${EXT_BRANCH}.zip --exclude='.git*' --exclude="xync.conf.ext" --strip-components 1 -C ${CWDIR}/update
			chmod +x ${CWDIR}/update/${APP_INIT}
			rm -f ${CWDIR}/update/${EXT_BRANCH}.zip
			cp -Rf ${CWDIR}/update/* ${CWDIR}/
			rm -R ${CWDIR}/update
		else
			echo "Extension is on the latest version!"
			rm -R ${CWDIR}/update
		fi
	fi
}

install_app() {
	mkdir -p "${APP_DIST}"
	echo "Fetching ${APP} package..."
	fetch -ao ${CWDIR}/${APP_BRANCH}.zip --no-verify-peer --timeout=30 ${APP_URL} || echo "[ERROR]: A problem has occurred while fetching ${APP} package."
	echo "Extracting ${APP} package..."
	tar -xf ${CWDIR}/${APP_BRANCH}.zip --exclude='.git*' --strip-components 1 -C ${APP_DIST} || echo "[ERROR]: A problem has occurred while extractig ${APPNAME} package."
	rm -f ${CWDIR}/${APP_BRANCH}.zip
	echo "Package Installed!"
}

add_postinit()
{
	# Check and generate temporary php script for postinit command.
	if ! grep -qw ${CWDIR}/${APP_INIT} ${XIGMANAS_CONFIG}; then
		touch ${CWDIR}/postinit || error_notify "Error: A problem has occurred while creating the postinit file."
		chmod +x ${CWDIR}/postinit
		cat << EOF > ${CWDIR}/postinit
<?php
require_once("config.inc");
require_once("functions.inc");
\$cmd = dirname(__FILE__)."/${SCRIPTNAME}";
\$name = "${PRDNAME} Extension";
\$comment = "Start ${PRDNAME} Replication Manager";
\$rc = &array_make_branch(\$config,'rc','param');
if(false === array_search_ex(\$cmd,\$rc,'cmd')):
	\$rc_param = [];
	\$rc_param['uuid'] = uuid();
	\$rc_param['name'] = \$name;
	\$rc_param['value'] = \$cmd;
	\$rc_param['comment'] = \$comment;
	\$rc_param['typeid'] = '2';
	\$rc_param['enable'] = true;
	\$rc[] = \$rc_param;
	write_config();
endif;
unset(\$rc);
?>
EOF

		# Execute temporary php script.
		echo "Creating postinit command..."
		php-cgi -f ${CWDIR}/postinit && rm ${CWDIR}/postinit || \
		error_notify "Error: A problem has occurred while executing postinit file."
		echo "Done!"
	fi
	if [ ! -f "${CWDIR}/${EXT_CONFIG}" ]; then
		# Set extension to enable by default.
		sysrc -f ${CWDIR}/${EXT_CONFIG} INSTALL_DIR=${CWDIR} >/dev/null 2>&1
	fi
}

add_symlinks()
{
	chmod 0750 ${CWDIR}
	chmod +x ${CWDIR}/${APP_INIT}
	if [ ! -f "${USRLOCAL}/sbin/${APP_INIT}" ]; then
		ln -fs ${CWDIR}/${APP_INIT} ${USRLOCAL}/sbin/${APP_INIT}
	fi
	# Initialize the extension gui.
	if [ -d "${CWDIR}/gui" ]; then
		if [ ! -d "${WWW}/ext" ]; then
			mkdir -p ${WWW}/ext
		fi
		mkdir -p /var/etc/xync
		ln -fhs ${CWDIR}/gui/ext/xync ${WWW}/ext/ || error_notify "Error: A problem has occurred while copying extension gui files."
		ln -fhs ${CWDIR}/${EXT_CONFIG} /var/etc/xync/${EXT_CONFIG} || error_notify "Error: A problem has occurred while linking extension config file."			
		ln -fhs ${CWDIR}/gui/xync-gui.php ${WWW}/ || error_notify "Error: A problem has occurred while linking extension gui files."
	fi
}

# Handle options.
while [ "$#" -gt 0 ]; do
    case "${1}" in
	-u|--update)
	    update_extension
		install_app
		exit 0
	    ;;
	-r|--remove)
	    remove_extension
		exit 0
	    ;;
	-x|--debug)
		set -x
		shift
		;;
	*) error_exit "[ERROR]: Unknown Option: \"${1}\""
		;;
    esac
done

echo "Initializing ${APP}..."

if [ ! -d "${APP_DIST}" ]; then
	install_extension
	install_app
fi	
add_postinit
add_symlinks
